
config_anto_cursor_modal_color_in_top_base = def_get_config_b32(vars_save_string_lit("anto_cursor_modal_color_in_top_base"));
config_anto_cursor_should_glow = def_get_config_b32(vars_save_string_lit("anto_cursor_should_glow"));
